output   = "gen/models"
wipe     = true
no-tests = true
add-enum-types = true
add-soft-deletes = true
add-panic-variants = true

[mysql]
  dbname  = "db"
  host    = "localhost"
  port    = 3306
  user    = "dbuser"
  pass    = "passw0rd"
  sslmode = "skip-verify"
  blacklist = ["migrations"]

[[types]]
  [types.match]
    tables = ['table1', 'table2']
    name = 'id'
  [types.replace]
    type = "ulid.ULID"
  [types.imports]
    third_party = ['"github.com/oklog/ulid/v2"']

[[types]]
  [types.match]
    name = "table1_id"
  [types.replace]
    type = "ulid.ULID"
  [types.imports]
    third_party = ['"github.com/oklog/ulid/v2"']
