version: "0.2"
ignorePaths:
  - README.md
  - README-sqlboiler.jp.md
  - "**/gen/**"
dictionaryDefinitions: []
dictionaries: []
words:
  - dbname
  - dbuser
  - devel
  - extendee
  - fkey
  - friendsofgo
  - gettingstarted
  - googleapis
  - hanako
  - hanko
  - Helperint
  - Idxs
  - jiro
  - messagev
  - oklog
  - passw
  - protocolbuffers
  - protoimpl
  - protoreflect
  - qmhelper
  - sato
  - sqlboiler
  - sslmode
  - strmangle
  - upserted
  - volatiletech
ignoreWords: []
import: []
