version: '3'

services:
  db:
    image: mysql:8.0.29
    ports:
      - ${MYSQL_PORT:-3306}:3306
    user: "${UID_GID:-1000:1000}"
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-mysql}
      - MYSQL_USER=${MYSQL_USER:-dbuser}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-dbpass}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-db}
    restart: always
    networks:
      - backend

networks:
  backend:
    driver: bridge
    name: backend_network
